// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int num = Integer.parseInt(args [0]);
		int countMore = 0;
		int countLess = 0;
for (int i = 0; i < num; i++)
{
double rando = Math.random();
 if (rando > 0.5)
 { 
   countMore ++;
 }
else{
	countLess ++;
}
}
//> 0.5: 47 times
//<= 0.5: 53 times
//Ratio: 0.8867924528301887
double Ratio = (double) countMore / countLess ;
System.out.println("> 0.5: " + countMore);
System.out.println("<= 0.5: " + countLess);
System.out.println("Ratio: " + Ratio);
	}
}
